import { Template } from './types';

export const TEMPLATES: Template[] = [
  // 01 — Soft Garden
  {
    id: 'soft-garden',
    name: 'Soft Garden',
    tagline: 'Flowers, handwritten notes, and soft morning sunlight',
    occasion: 'birthday',
    aesthetic: ['soft', 'romantic', 'cute'],
    description: 'A delicate pastel palette of cream, pressed rose petals, and handwritten margins. Perfect for someone who brings warmth into your everyday life.',
    previewImage: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80',
    theme: {
      background: '#FAF7F2',
      foreground: '#2A2421',
      accent: '#C97A6E',
      accentSoft: '#F9EBE8',
      paperTone: '#FDFBF7',
      cardBackground: '#FFFFFF',
      borderStyle: '1px solid rgba(201, 122, 110, 0.2)',
      fontFamilySerif: 'var(--font-serif)',
      fontFamilySans: 'var(--font-body)',
      fontFamilyHand: 'var(--font-hand)',
    },
    defaultMusicTrack: 'acoustic-sunbeams',
    defaultSections: [
      {
        id: 'sg-hero',
        type: 'hero',
        title: 'Happy Birthday',
        subtitle: 'for the girl who makes ordinary days feel soft ♡',
        dateText: '06 October',
        heroPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=80',
        badgeText: 'A little corner of love for you',
        audioHint: 'Acoustic Sunbeams',
        layout: 'editorial-split',
      },
      {
        id: 'sg-letter',
        type: 'letter',
        greeting: 'Dear Aanchal,',
        paragraphs: [
          'I wanted to make something for you that you could keep forever. Not just another card you tuck into a drawer, but a quiet space filled with all the little things that make you so unforgettable.',
          'Thank you for laughing at my silliest jokes, for listening to me ramble, and for being the kindest, brightest soul in every room you enter.',
          'Here is to another year of late night conversations, sunny walks, and watching you blossom into everything you dream of.'
        ],
        closing: 'All my love, always,',
        handwrittenSignature: 'Alok ♡',
        waxSeal: true,
        paperStyle: 'lined',
      },
      {
        id: 'sg-polaroids',
        type: 'polaroidCollage',
        title: 'Treasured Moments',
        subtitle: 'snapshots from our favorite days together',
        polaroids: [
          {
            url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80',
            caption: 'the day we got lost in the botanical garden',
            date: 'May 14',
            rotation: -2.5,
            washiColor: 'rose',
          },
          {
            url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
            caption: 'your brightest golden hour smile',
            date: 'July 22',
            rotation: 2.1,
            washiColor: 'sage',
          },
          {
            url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80',
            caption: 'rainy coffee shop talks that went until midnight',
            date: 'Sept 03',
            rotation: -1.2,
            washiColor: 'gold',
          },
        ],
      },
      {
        id: 'sg-favorite-things',
        type: 'favoriteThings',
        title: 'Favorite Things About You',
        subtitle: 'the tiny details I notice every single day',
        items: [
          { category: 'Your Smile', value: 'The way your whole face crinkles when you laugh really hard.', note: 'My favorite sight' },
          { category: 'Your Warmth', value: 'How you always remember how people take their tea.', note: 'Pure kindness' },
          { category: 'Your Taste', value: 'Vintage bookshops, fresh peonies, and indie playlists.', note: 'Impeccable' },
          { category: 'Your Heart', value: 'The quiet gentleness you extend to everyone around you.', note: 'Rare & beautiful' },
        ],
      },
      {
        id: 'sg-ending',
        type: 'ending',
        message: 'May this year be as gentle and luminous as you are. Happy Birthday ♡',
        subtext: 'You are loved beyond measure.',
        showDrewtifullBranding: true,
      },
    ],
  },

  // 02 — Film Diary
  {
    id: 'film-diary',
    name: 'Film Diary',
    tagline: '35mm grain, vintage timestamps, and cinematic nostalgia',
    occasion: 'birthday',
    aesthetic: ['cinematic', 'vintage', 'editorial'],
    description: 'Inspired by analog film negatives, warm Kodak tones, and tactile memories captured frame by frame.',
    previewImage: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    theme: {
      background: '#181615',
      foreground: '#F5EFE6',
      accent: '#D4AF37',
      accentSoft: '#2B2620',
      paperTone: '#221F1D',
      cardBackground: '#1C1A18',
      borderStyle: '1px solid rgba(212, 175, 55, 0.25)',
      fontFamilySerif: 'var(--font-serif)',
      fontFamilySans: 'var(--font-body)',
      fontFamilyHand: 'var(--font-hand)',
      dark: true,
    },
    defaultMusicTrack: 'lofi-memories',
    defaultSections: [
      {
        id: 'fd-hero',
        type: 'hero',
        title: 'Roll 24 // Aanchal',
        subtitle: 'raw frames & unhurried moments',
        dateText: 'ISO 400 · 35mm Film',
        heroPhoto: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=1000&q=80',
        badgeText: 'Archive 2026',
        audioHint: 'Vintage Tape & Coffee',
        layout: 'film-cover',
      },
      {
        id: 'fd-filmstrip',
        type: 'filmStrip',
        title: 'Contact Sheet 01',
        subtitle: 'unfiltered memories frozen on 35mm stock',
        filmFormat: '35mm',
        frames: [
          {
            url: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?auto=format&fit=crop&w=800&q=80',
            caption: 'candid laugh outside the metro',
            timestamp: '17:42:09',
            frameNumber: 'EXP 01',
          },
          {
            url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
            caption: 'the glow before the storm',
            timestamp: '18:15:33',
            frameNumber: 'EXP 02',
          },
          {
            url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
            caption: 'midnight diner fries & milkshakes',
            timestamp: '23:58:12',
            frameNumber: 'EXP 03',
          },
        ],
      },
      {
        id: 'fd-letter',
        type: 'letter',
        greeting: 'Dear favorite human,',
        paragraphs: [
          'If our year together was a spool of film, there wouldnt be a single wasted exposure.',
          'You turn ordinary grocery store runs into cinema. You make every rainy afternoon feel like a scene worth replaying.',
          'Happy birthday to the person who makes life look so effortlessly vivid.'
        ],
        closing: 'Captured with love,',
        handwrittenSignature: 'Yours always 🎞️',
        paperStyle: 'parchment',
      },
      {
        id: 'fd-ending',
        type: 'ending',
        message: 'To many more rolls and memories unspooled together.',
        subtext: 'Happy Birthday ♡',
        showDrewtifullBranding: true,
      },
    ],
  },

  // 03 — Scrapbook Birthday
  {
    id: 'scrapbook-birthday',
    name: 'Scrapbook Birthday',
    tagline: 'Washi tape, polaroid scraps, stickers, and inside jokes',
    occasion: 'birthday',
    aesthetic: ['scrapbook', 'playful', 'cute'],
    description: 'Charming handcrafted paper textures, playful washi tape, candid polaroids, and doodle badges.',
    previewImage: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    theme: {
      background: '#FAF5ED',
      foreground: '#231E1B',
      accent: '#B95B3B',
      accentSoft: '#F6E5DE',
      paperTone: '#FFFFFF',
      cardBackground: '#FFFFFF',
      borderStyle: '1px dashed rgba(185, 91, 59, 0.3)',
      fontFamilySerif: 'var(--font-serif)',
      fontFamilySans: 'var(--font-body)',
      fontFamilyHand: 'var(--font-hand)',
    },
    defaultMusicTrack: 'acoustic-sunbeams',
    defaultSections: [
      {
        id: 'sb-hero',
        type: 'hero',
        title: 'Happy Birthday!',
        subtitle: 'a little handmade scrapbook of my favorite person in the world',
        dateText: 'Special Edition · 2026',
        heroPhoto: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1000&q=80',
        badgeText: 'Handmade with love ♡',
        layout: 'scrapbook-header',
      },
      {
        id: 'sb-polaroids',
        type: 'polaroidCollage',
        title: 'The Evidence',
        subtitle: 'proof that we have the most fun together',
        polaroids: [
          {
            url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
            caption: 'trying not to burst out laughing in public',
            date: 'Spring 2025',
            rotation: -3.5,
            washiColor: 'rose',
          },
          {
            url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80',
            caption: 'the festival where we danced until our feet hurt',
            date: 'Summer 2025',
            rotation: 2.8,
            washiColor: 'sage',
          },
          {
            url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80',
            caption: 'matching sweaters (unplanned!)',
            date: 'Winter 2025',
            rotation: -1.5,
            washiColor: 'gold',
          },
        ],
      },
      {
        id: 'sb-reasons',
        type: 'reasons',
        title: '3 Reasons Why You Are Unmatched',
        subtitle: 'backed by science and personal experience',
        items: [
          { number: 1, title: 'Your Laugh is Contagious', text: 'You can cause a 10-minute laughing fit with just one eyebrow raise.', doodle: '✨' },
          { number: 2, title: 'Top-Tier Food Radar', text: 'You always pick the exact best thing on every restaurant menu.', doodle: '🍕' },
          { number: 3, title: 'The Kindest Soul', text: 'You show up for people in ways that make the world feel softer.', doodle: '💛' },
        ],
      },
      {
        id: 'sb-ending',
        type: 'ending',
        message: 'Happy Birthday, bestie! Keep shining like the absolute star you are.',
        subtext: 'Love you to the moon and back ♡',
        showDrewtifullBranding: true,
      },
    ],
  },

  // 04 — Digital Love Letter
  {
    id: 'digital-love-letter',
    name: 'Digital Love Letter',
    tagline: 'Quiet editorial poetry, generous whitespace, and intimate letters',
    occasion: 'anniversary',
    aesthetic: ['minimal', 'editorial', 'romantic'],
    description: 'Stripped of clutter. Large, timeless serif typography, warm linen paper, and heartfelt words that breathe.',
    previewImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
    theme: {
      background: '#FBF9F5',
      foreground: '#1F1B18',
      accent: '#9E4E3B',
      accentSoft: '#F6EAE6',
      paperTone: '#FFFDF9',
      cardBackground: '#FFFDF9',
      borderStyle: '1px solid rgba(40, 30, 20, 0.08)',
      fontFamilySerif: 'var(--font-display)',
      fontFamilySans: 'var(--font-body)',
      fontFamilyHand: 'var(--font-hand)',
    },
    defaultMusicTrack: 'warm-piano-waltz',
    defaultSections: [
      {
        id: 'dll-hero',
        type: 'hero',
        title: 'For the person who makes ordinary days feel holy.',
        subtitle: 'A quiet letter from me to you',
        dateText: 'October 2026',
        heroPhoto: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1000&q=80',
        badgeText: 'An intimate note',
        layout: 'centered',
      },
      {
        id: 'dll-letter',
        type: 'letter',
        greeting: 'My dearest,',
        paragraphs: [
          'If someone asked me to define what home feels like, I would not describe a place or four walls. I would describe the sound of your footsteps in the hallway, the way you make coffee before the sun is up, and how all my racing thoughts settle whenever you take my hand.',
          'Loving you has been the easiest, quietest, most natural thing I have ever done. With you, I never have to perform or be anyone other than who I am.',
          'Thank you for loving me patiently, generously, and without condition. Today and every day, I choose you.'
        ],
        closing: 'With all my heart and all my years,',
        handwrittenSignature: 'Forever yours ♡',
        waxSeal: true,
        paperStyle: 'parchment',
      },
      {
        id: 'dll-quote',
        type: 'quote',
        quoteText: 'In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine.',
        author: 'Maya Angelou',
        subtext: 'Words that remind me of you every day',
      },
      {
        id: 'dll-ending',
        type: 'ending',
        message: 'Happy Anniversary, my love. Here is to our forever.',
        subtext: 'Always & endlessly',
        showDrewtifullBranding: true,
      },
    ],
  },

  // 05 — Our Story (Timeline)
  {
    id: 'our-story',
    name: 'Our Story',
    tagline: 'An interactive romantic journey from the day we met until today',
    occasion: 'anniversary',
    aesthetic: ['editorial', 'romantic', 'cinematic'],
    description: 'Walk through the chapters of your love story: the first spark, the unforgettable dates, and where you are headed next.',
    previewImage: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80',
    theme: {
      background: '#F7F3ED',
      foreground: '#24201D',
      accent: '#C46D4E',
      accentSoft: '#F6EBE5',
      paperTone: '#FDFBF7',
      cardBackground: '#FFFFFF',
      borderStyle: '1px solid rgba(196, 109, 78, 0.2)',
      fontFamilySerif: 'var(--font-serif)',
      fontFamilySans: 'var(--font-body)',
      fontFamilyHand: 'var(--font-hand)',
    },
    defaultMusicTrack: 'warm-piano-waltz',
    defaultSections: [
      {
        id: 'os-hero',
        type: 'hero',
        title: 'Two Years with You',
        subtitle: 'every chapter better than the last',
        dateText: '730 days of us',
        heroPhoto: 'https://images.unsplash.com/photo-1494774157365-9e04c6720e47?auto=format&fit=crop&w=1000&q=80',
        badgeText: 'Our Timeline',
        layout: 'editorial-split',
      },
      {
        id: 'os-timeline',
        type: 'timeline',
        title: 'Chapters of Us',
        subtitle: 'how a chance conversation turned into my entire world',
        events: [
          {
            date: 'October 12, 2024',
            title: 'The First Hello',
            description: 'A crowded bookshop on a rainy Tuesday. We reached for the same poetry anthology, and you joked that I had good taste.',
            image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
          },
          {
            date: 'November 03, 2024',
            title: 'Our First Official Date',
            description: 'Three hours turned into five. The restaurant staff politely stacked the chairs around us while we lost track of time entirely.',
            image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80',
          },
          {
            date: 'Summer 2025',
            title: 'The Seaside Getaway',
            description: 'Salt in our hair, sharing midnight gelato by the boardwalk, watching shooting stars wrap around the horizon.',
            image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
          },
          {
            date: 'Today & Beyond',
            title: 'Building Our Life',
            description: 'Cooking dinners, laughing through messy days, and knowing there is no one else I would rather share this life with.',
          },
        ],
      },
      {
        id: 'os-ending',
        type: 'ending',
        message: 'The best chapters of our story are the ones we haven’t written yet.',
        subtext: 'Happy Anniversary, my darling.',
        showDrewtifullBranding: true,
      },
    ],
  },

  // 06 — Before I Ask (Proposal)
  {
    id: 'before-i-ask',
    name: 'Before I Ask',
    tagline: 'A cinematic progression culminating in the most important question',
    occasion: 'proposal',
    aesthetic: ['cinematic', 'romantic', 'editorial'],
    description: 'Builds emotional anticipation step by step through memories and quiet intimacy, before presenting the big question with confetti and interactive joy.',
    previewImage: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=800&q=80',
    theme: {
      background: '#F9F5F0',
      foreground: '#231F1D',
      accent: '#B8863A',
      accentSoft: '#FAF3E5',
      paperTone: '#FFFFFF',
      cardBackground: '#FFFFFF',
      borderStyle: '1px solid rgba(184, 134, 58, 0.25)',
      fontFamilySerif: 'var(--font-serif)',
      fontFamilySans: 'var(--font-body)',
      fontFamilyHand: 'var(--font-hand)',
    },
    defaultMusicTrack: 'starlight-musicbox',
    defaultSections: [
      {
        id: 'bia-hero',
        type: 'hero',
        title: 'There is something I need to ask you...',
        subtitle: 'take a breath and scroll slowly with me ♡',
        dateText: 'A very special moment',
        heroPhoto: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=1000&q=80',
        badgeText: 'Listen closely',
        layout: 'centered',
      },
      {
        id: 'bia-reveal',
        type: 'proposalReveal',
        introTitle: 'Before I ask...',
        memories: [
          { text: 'I remember the first time you laughed so hard tears rolled down your cheeks. In that moment, I knew I was in trouble.' },
          { text: 'I remember walking in the rain with you, cold and soaking wet, and feeling warmer than I have ever felt in my life.' },
          { text: 'I realized that every dream I have for the future has your hand in mine.' }
        ],
        suspenseText: 'There is one more thing I want to ask you...',
        questionText: 'Will you marry me, Maya?',
        celebrationTitle: 'She said YES! 💍✨',
        celebrationMessage: 'The beginning of our greatest adventure together.',
      },
      {
        id: 'bia-ending',
        type: 'ending',
        message: 'Forever and always, from this day forward.',
        subtext: 'Our next chapter starts now ♡',
        showDrewtifullBranding: true,
      },
    ],
  },

  // 07 — Our Little Universe
  {
    id: 'our-little-universe',
    name: 'Our Little Universe',
    tagline: 'Midnight skies, stardust coordinates, and celestial memories',
    occasion: 'proposal',
    aesthetic: ['dark', 'romantic', 'cinematic'],
    description: 'A breathtaking nocturnal sanctuary where your photos shine like constellations in the deep velvet night.',
    previewImage: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80',
    theme: {
      background: '#0D111A',
      foreground: '#E8ECF5',
      accent: '#F3D27E',
      accentSoft: '#1F2738',
      paperTone: '#131926',
      cardBackground: '#131926',
      borderStyle: '1px solid rgba(243, 210, 126, 0.25)',
      fontFamilySerif: 'var(--font-serif)',
      fontFamilySans: 'var(--font-body)',
      fontFamilyHand: 'var(--font-hand)',
      dark: true,
    },
    defaultMusicTrack: 'starlight-musicbox',
    defaultSections: [
      {
        id: 'olu-hero',
        type: 'hero',
        title: 'Written in the Stars',
        subtitle: 'you are my favorite constellation in an endless sky',
        dateText: 'Coordinates: 40.7128° N, 74.0060° W',
        heroPhoto: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1000&q=80',
        badgeText: 'Celestial map',
        layout: 'celestial',
      },
      {
        id: 'olu-starmap',
        type: 'starMap',
        title: 'Our Constellations',
        subtitle: 'every star marks a night I fell deeper in love with you',
        starQuote: 'Two wandering souls, caught in each other’s gravity.',
        coordinatesText: 'Alpha Centauri · Orbiting Together',
        photosAsStars: [
          { url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80', label: 'The First Spark', x: 22, y: 35 },
          { url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80', label: 'Under the Pier', x: 50, y: 20 },
          { url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=400&q=80', label: 'Our Midnight Beach', x: 78, y: 48 },
        ],
      },
      {
        id: 'olu-letter',
        type: 'letter',
        greeting: 'To my North Star,',
        paragraphs: [
          'In a universe of billions of galaxies and infinite possibilities, I got to find you.',
          'No matter how dark or uncertain the world gets, you are the constant light that guides me home.',
          'I love you beyond the edge of what words can hold.'
        ],
        closing: 'Always orbiting you,',
        handwrittenSignature: 'Your Stargazer ✨',
        waxSeal: true,
      },
      {
        id: 'olu-ending',
        type: 'ending',
        message: 'You and me, across every galaxy and every lifetime.',
        subtext: 'Endlessly yours',
        showDrewtifullBranding: true,
      },
    ],
  },

  // 08 — My Favorite Human (Friendship)
  {
    id: 'my-favorite-human',
    name: 'My Favorite Human',
    tagline: 'Memes, chaos, inside jokes, and unwavering loyalty',
    occasion: 'friendship',
    aesthetic: ['playful', 'scrapbook', 'cute'],
    description: 'An affectionate, hilarious homage to your best friend with polaroids, silly annotations, and real gratitude.',
    previewImage: 'https://images.unsplash.com/photo-1543807535-eceef0bc6599?auto=format&fit=crop&w=800&q=80',
    theme: {
      background: '#FAF6EE',
      foreground: '#262220',
      accent: '#6E8774',
      accentSoft: '#E8F0EA',
      paperTone: '#FFFFFF',
      cardBackground: '#FFFFFF',
      borderStyle: '1px solid rgba(110, 135, 116, 0.25)',
      fontFamilySerif: 'var(--font-serif)',
      fontFamilySans: 'var(--font-body)',
      fontFamilyHand: 'var(--font-hand)',
    },
    defaultMusicTrack: 'acoustic-sunbeams',
    defaultSections: [
      {
        id: 'mfh-hero',
        type: 'hero',
        title: 'To My Favorite Human On Earth',
        subtitle: 'an official appreciation digital artifact for Maya',
        dateText: 'Established 2018',
        heroPhoto: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1000&q=80',
        badgeText: 'Best Friend Hall of Fame 🏆',
        layout: 'scrapbook-header',
      },
      {
        id: 'mfh-reasons',
        type: 'reasons',
        title: 'Why You Deserve A Trophy',
        subtitle: 'verified by unanimous peer review',
        items: [
          { number: 1, title: 'Instant De-escalation', text: 'You can talk me off any panic cliff in 30 seconds flat.', doodle: '🌿' },
          { number: 2, title: 'Snack Telepathy', text: 'You show up with the exact iced matcha latte I was craving.', doodle: '🍵' },
          { number: 3, title: 'Ride or Die Energy', text: 'You would help me move a heavy couch with zero notice.', doodle: '💪' },
        ],
      },
      {
        id: 'mfh-polaroids',
        type: 'polaroidCollage',
        title: 'Chaos Archive',
        subtitle: 'never show these to anyone in public',
        polaroids: [
          {
            url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
            caption: 'crying from laughing so hard at 2 AM',
            date: 'Summer 2025',
            rotation: -2.8,
            washiColor: 'sage',
          },
          {
            url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80',
            caption: 'road trip where we only listened to 2000s pop',
            date: 'Fall 2025',
            rotation: 3.2,
            washiColor: 'gold',
          },
        ],
      },
      {
        id: 'mfh-ending',
        type: 'ending',
        message: 'Could not do this crazy life without you. Love you forever!',
        subtext: 'Your partner in crime ♡',
        showDrewtifullBranding: true,
      },
    ],
  },

  // 09 — Just Because
  {
    id: 'just-because',
    name: 'Just Because',
    tagline: 'No anniversary, no holiday. Simply because I love you today.',
    occasion: 'just-because',
    aesthetic: ['minimal', 'soft', 'editorial'],
    description: 'The unexpected gift. A quiet, heartfelt reminder that someone is thinking of them on an ordinary Tuesday.',
    previewImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    theme: {
      background: '#FDFBF7',
      foreground: '#231F1E',
      accent: '#B65A4B',
      accentSoft: '#F8ECE9',
      paperTone: '#FFFFFF',
      cardBackground: '#FFFFFF',
      borderStyle: '1px solid rgba(182, 90, 75, 0.15)',
      fontFamilySerif: 'var(--font-serif)',
      fontFamilySans: 'var(--font-body)',
      fontFamilyHand: 'var(--font-hand)',
    },
    defaultMusicTrack: 'warm-piano-waltz',
    defaultSections: [
      {
        id: 'jb-hero',
        type: 'hero',
        title: 'You don’t need a reason to be celebrated.',
        subtitle: 'a little reminder that you are deeply loved today',
        dateText: 'Just an ordinary Tuesday',
        heroPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=80',
        badgeText: 'Just because ♡',
        layout: 'editorial-split',
      },
      {
        id: 'jb-letter',
        type: 'letter',
        greeting: 'Hey you,',
        paragraphs: [
          'There is no special occasion today. No calendar alert, no anniversary, no birthday.',
          'I just saw a flower outside that reminded me of you, and I wanted to make you something small to remind you that your existence makes my whole world softer and brighter.',
          'I hope you take a deep breath today, drink your favorite coffee, and remember how truly extraordinary you are.'
        ],
        closing: 'Always rooting for you,',
        handwrittenSignature: 'Me ♡',
        waxSeal: false,
      },
      {
        id: 'jb-ending',
        type: 'ending',
        message: 'That is all. Go have the gentlest day ♡',
        subtext: 'Thinking of you always.',
        showDrewtifullBranding: true,
      },
    ],
  },

  // 10 — Cute & Cozy
  {
    id: 'cute-and-cozy',
    name: 'Cute & Cozy',
    tagline: 'Warm sweaters, hot cocoa, doodle hearts, and soft memories',
    occasion: 'birthday',
    aesthetic: ['cute', 'playful', 'soft'],
    description: 'Gentle rounded frames, whimsical doodle accents, and warm amber tones that feel like a hug.',
    previewImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    theme: {
      background: '#FDF7F0',
      foreground: '#2F2622',
      accent: '#DE7C5A',
      accentSoft: '#FCECE6',
      paperTone: '#FFFDF9',
      cardBackground: '#FFFFFF',
      borderStyle: '1px solid rgba(222, 124, 90, 0.2)',
      fontFamilySerif: 'var(--font-serif)',
      fontFamilySans: 'var(--font-body)',
      fontFamilyHand: 'var(--font-hand)',
    },
    defaultMusicTrack: 'acoustic-sunbeams',
    defaultSections: [
      {
        id: 'cc-hero',
        type: 'hero',
        title: 'Happy Birthday, Sunshine!',
        subtitle: 'warmest wishes, warm tea, and endless cozy vibes',
        dateText: 'A cozy celebration',
        heroPhoto: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1000&q=80',
        badgeText: 'Cup of warmth ☕',
        layout: 'centered',
      },
      {
        id: 'cc-favorite-things',
        type: 'favoriteThings',
        title: 'Cozy Things That Feel Like You',
        subtitle: 'the softest things in the universe',
        items: [
          { category: 'Scent', value: 'Fresh cinnamon buns & lavender candles.' },
          { category: 'Vibe', value: 'Oversized knit cardigans on crisp autumn mornings.' },
          { category: 'Superpower', value: 'Giving the absolute warmest hugs that melt away any bad day.' },
        ],
      },
      {
        id: 'cc-ending',
        type: 'ending',
        message: 'May your year be filled with cozy socks, warm treats, and endless love!',
        subtext: 'Happy Birthday ♡',
        showDrewtifullBranding: true,
      },
    ],
  },

  // 11 — Memory Journal
  {
    id: 'memory-journal',
    name: 'Memory Journal',
    tagline: 'Linen covers, pressed petals, and honest handwritten reflections',
    occasion: 'graduation',
    aesthetic: ['editorial', 'vintage', 'soft'],
    description: 'An elegant bound journal aesthetic celebrating milestones, growth, and the beautiful next chapter.',
    previewImage: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=80',
    theme: {
      background: '#F6F1EA',
      foreground: '#231E19',
      accent: '#6A7B68',
      accentSoft: '#E6EFE5',
      paperTone: '#FAF6F0',
      cardBackground: '#FAF6F0',
      borderStyle: '1px solid rgba(106, 123, 104, 0.2)',
      fontFamilySerif: 'var(--font-serif)',
      fontFamilySans: 'var(--font-body)',
      fontFamilyHand: 'var(--font-hand)',
    },
    defaultMusicTrack: 'warm-piano-waltz',
    defaultSections: [
      {
        id: 'mj-hero',
        type: 'hero',
        title: 'For the Next Chapter',
        subtitle: 'celebrating every late night, every victory, and everything to come',
        dateText: 'Class of 2026',
        heroPhoto: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1000&q=80',
        badgeText: 'Milestone edition',
        layout: 'editorial-split',
      },
      {
        id: 'mj-letter',
        type: 'letter',
        greeting: 'To our graduate,',
        paragraphs: [
          'Looking back at how far you have come, we are so incredibly proud of the resilience, grace, and intellect you have shown at every step.',
          'You worked when nobody was watching, kept going when things were tough, and emerged stronger and wiser.',
          'The world is waiting for your gifts. Step into your next chapter with your chin high and your heart open.'
        ],
        closing: 'With all our pride and admiration,',
        handwrittenSignature: 'Your Family ♡',
        waxSeal: true,
      },
      {
        id: 'mj-ending',
        type: 'ending',
        message: 'Congratulations! The world is yours to shape.',
        subtext: 'So proud of you.',
        showDrewtifullBranding: true,
      },
    ],
  },

  // 12 — Farewell Memories
  {
    id: 'farewell-memories',
    name: 'Farewell & Keep in Touch',
    tagline: 'Miles apart but never distant. Celebrating the memories we keep.',
    occasion: 'farewell',
    aesthetic: ['vintage', 'romantic', 'soft'],
    description: 'For someone moving away, embarking on a new journey, or starting a new job. A keepsake of love across any distance.',
    previewImage: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80',
    theme: {
      background: '#F9F6F0',
      foreground: '#2A2522',
      accent: '#B06543',
      accentSoft: '#F6EAE3',
      paperTone: '#FFFFFF',
      cardBackground: '#FFFFFF',
      borderStyle: '1px solid rgba(176, 101, 67, 0.2)',
      fontFamilySerif: 'var(--font-serif)',
      fontFamilySans: 'var(--font-body)',
      fontFamilyHand: 'var(--font-hand)',
    },
    defaultMusicTrack: 'acoustic-sunbeams',
    defaultSections: [
      {
        id: 'fm-hero',
        type: 'hero',
        title: 'Until We Meet Again',
        subtitle: 'distance means so little when friendship means so much',
        dateText: 'Safe Travels · 2026',
        heroPhoto: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1000&q=80',
        badgeText: 'A little keepsake for your journey',
        layout: 'centered',
      },
      {
        id: 'fm-polaroids',
        type: 'polaroidCollage',
        title: 'Memories We Will Always Keep',
        subtitle: 'the good times that stay with us forever',
        polaroids: [
          {
            url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80',
            caption: 'our legendary rooftop sunset dinners',
            date: 'Last Summer',
            rotation: -2,
            washiColor: 'gold',
          },
          {
            url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
            caption: 'promise you will call whenever you land',
            date: 'October',
            rotation: 2.5,
            washiColor: 'rose',
          },
        ],
      },
      {
        id: 'fm-ending',
        type: 'ending',
        message: 'No distance can change what you mean to us. Go shine!',
        subtext: 'We are always right here ♡',
        showDrewtifullBranding: true,
      },
    ],
  },
];

export function getTemplateById(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

export function getTemplatesByOccasion(occasion: string): Template[] {
  if (occasion === 'all') return TEMPLATES;
  return TEMPLATES.filter((t) => t.occasion === occasion);
}
